# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 12:58
from __future__ import unicode_literals
from django.db import migrations
from event.models import Event

class Migration(migrations.Migration):

    def add_events(apps, schema_editor):
        """
        add fewevents to database
        """

        for i in range(5):
            model = Event(name='test ' + str(i), lat='123.45678', lon='456.4234')
            model.save()


    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_events),
    ]
