# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 16:08
from __future__ import unicode_literals
import hashlib
from django.db import migrations
from user.models import User
from django.conf import settings

class Migration(migrations.Migration):
    
    def add_user(apps, schema_editor):
        """
        add admin user for test, login: admin, pass: admin
        """
        password = 'admin' + settings.PASSWORD_SALT
        password_hash = hashlib.md5(password.encode('utf-8'))
        model = User(username='admin', password=password_hash.hexdigest())
        model.save()

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
